Silicon/Marvell: fix SMBIOS type 7 structures
Commit [1] updated the uses of SMBIOS type 4 and 7 structures for
Silicon/Marvell but forgot to actually use SMBIOS_CACHE_SIZE_2
structures (introduced in commit [2]).

Compiling this platform fails with error:

    edk2-platforms/Silicon/Marvell/Drivers/SmbiosPlatformDxe/SmbiosPlatformDxe.c:231:3: error: unsigned conversion from ‘int’ to ‘unsigned char:1’ changes value from ‘48’ to ‘0’ [-Werror=overflow]
      231 |   48,    //48k installed
          |   ^~

This commit fixes this issue.

[1] https://github.com/tianocore/edk2-platforms/commit/8390e51f56c416465a1ebb81e320a89b539cca30
[2] https://github.com/tianocore/edk2/commit/dfac150bdfc059e486f14072c5249d4d7c200c38

Signed-off-by: Julien Olivain <ju.o@free.fr>