KabylakeSiliconPkg: Fix mismatched function declaration
On building Kabylake platforms in GCC5, we enounter (abbreviated):

SystemAgent/Library/PeiSaPolicyLib/MrcOemPlatform.c:610:1: error: conflicting types for ‘CheckPoint’
due to enum/integer mismatch; have ‘MrcStatus(void *, MrcOemStatusCommand,  void *)’ [-Werror=enum-int-mismatch]

SystemAgent/Library/PeiSaPolicyLib/MrcOemPlatform.h:262:1: note: previous declaration of ‘CheckPoint’
with type ‘UINT32(void *, UINT32,  void *)’ {aka ‘unsigned int(void *, unsigned int,  void *)’}

Fix the header declaration to match the function definition, including
having the more specific enum types.

Signed-off-by: Mike Beaton <mjsbeaton@gmail.com>